/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct PluginLolTrophiesApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> PluginLolTrophiesApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> PluginLolTrophiesApiClient<C> {
        PluginLolTrophiesApiClient {
            configuration,
        }
    }
}

pub trait PluginLolTrophiesApi {
    fn get_lol_trophies_v1_current_summoner_trophies_profile(&self, ) -> Box<dyn Future<Item = crate::models::LolTrophiesTrophyProfileData, Error = Error<serde_json::Value>>>;
    fn get_lol_trophies_v1_players_by_puuid_trophies_profile(&self, puuid: &str) -> Box<dyn Future<Item = crate::models::LolTrophiesTrophyProfileData, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>PluginLolTrophiesApi for PluginLolTrophiesApiClient<C> {
    fn get_lol_trophies_v1_current_summoner_trophies_profile(&self, ) -> Box<dyn Future<Item = crate::models::LolTrophiesTrophyProfileData, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/lol-trophies/v1/current-summoner/trophies/profile".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_lol_trophies_v1_players_by_puuid_trophies_profile(&self, puuid: &str) -> Box<dyn Future<Item = crate::models::LolTrophiesTrophyProfileData, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/lol-trophies/v1/players/{puuid}/trophies/profile".to_string())
        ;
        req = req.with_path_param("puuid".to_string(), puuid.to_string());

        req.execute(self.configuration.borrow())
    }

}
