/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct PluginManagerApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> PluginManagerApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> PluginManagerApiClient<C> {
        PluginManagerApiClient {
            configuration,
        }
    }
}

pub trait PluginManagerApi {
    fn get_by_plugin_assets_by_path(&self, plugin: &str, path: &str, if_none_match: Option<&str>) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>>;
    fn get_plugin_manager_v1_external_plugins_availability(&self, ) -> Box<dyn Future<Item = crate::models::ExternalPluginsResource, Error = Error<serde_json::Value>>>;
    fn get_plugin_manager_v1_status(&self, ) -> Box<dyn Future<Item = crate::models::PluginManagerResource, Error = Error<serde_json::Value>>>;
    fn get_plugin_manager_v2_descriptions(&self, ) -> Box<dyn Future<Item = Vec<crate::models::PluginDescriptionResource>, Error = Error<serde_json::Value>>>;
    fn get_plugin_manager_v2_descriptions_by_plugin(&self, plugin: &str) -> Box<dyn Future<Item = crate::models::PluginDescriptionResource, Error = Error<serde_json::Value>>>;
    fn get_plugin_manager_v2_plugins(&self, ) -> Box<dyn Future<Item = Vec<crate::models::PluginResource>, Error = Error<serde_json::Value>>>;
    fn get_plugin_manager_v2_plugins_by_plugin(&self, plugin: &str) -> Box<dyn Future<Item = crate::models::PluginResource, Error = Error<serde_json::Value>>>;
    fn get_plugin_manager_v3_plugins_manifest(&self, ) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>>;
    fn head_by_plugin_assets_by_path(&self, plugin: &str, path: &str, if_none_match: Option<&str>) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>PluginManagerApi for PluginManagerApiClient<C> {
    fn get_by_plugin_assets_by_path(&self, plugin: &str, path: &str, if_none_match: Option<&str>) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/{plugin}/assets/{path}".to_string())
        ;
        req = req.with_path_param("plugin".to_string(), plugin.to_string());
        req = req.with_path_param("path".to_string(), path.to_string());
        if let Some(param_value) = if_none_match {
            req = req.with_header_param("if-none-match".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    fn get_plugin_manager_v1_external_plugins_availability(&self, ) -> Box<dyn Future<Item = crate::models::ExternalPluginsResource, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/plugin-manager/v1/external-plugins/availability".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_plugin_manager_v1_status(&self, ) -> Box<dyn Future<Item = crate::models::PluginManagerResource, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/plugin-manager/v1/status".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_plugin_manager_v2_descriptions(&self, ) -> Box<dyn Future<Item = Vec<crate::models::PluginDescriptionResource>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/plugin-manager/v2/descriptions".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_plugin_manager_v2_descriptions_by_plugin(&self, plugin: &str) -> Box<dyn Future<Item = crate::models::PluginDescriptionResource, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/plugin-manager/v2/descriptions/{plugin}".to_string())
        ;
        req = req.with_path_param("plugin".to_string(), plugin.to_string());

        req.execute(self.configuration.borrow())
    }

    fn get_plugin_manager_v2_plugins(&self, ) -> Box<dyn Future<Item = Vec<crate::models::PluginResource>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/plugin-manager/v2/plugins".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_plugin_manager_v2_plugins_by_plugin(&self, plugin: &str) -> Box<dyn Future<Item = crate::models::PluginResource, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/plugin-manager/v2/plugins/{plugin}".to_string())
        ;
        req = req.with_path_param("plugin".to_string(), plugin.to_string());

        req.execute(self.configuration.borrow())
    }

    fn get_plugin_manager_v3_plugins_manifest(&self, ) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/plugin-manager/v3/plugins-manifest".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn head_by_plugin_assets_by_path(&self, plugin: &str, path: &str, if_none_match: Option<&str>) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Head, "/{plugin}/assets/{path}".to_string())
        ;
        req = req.with_path_param("plugin".to_string(), plugin.to_string());
        req = req.with_path_param("path".to_string(), path.to_string());
        if let Some(param_value) = if_none_match {
            req = req.with_header_param("if-none-match".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

}
