/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct PluginLolLeagueSessionApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> PluginLolLeagueSessionApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> PluginLolLeagueSessionApiClient<C> {
        PluginLolLeagueSessionApiClient {
            configuration,
        }
    }
}

pub trait PluginLolLeagueSessionApi {
    fn get_lol_league_session_v1_league_session_token(&self, ) -> Box<dyn Future<Item = String, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>PluginLolLeagueSessionApi for PluginLolLeagueSessionApiClient<C> {
    fn get_lol_league_session_v1_league_session_token(&self, ) -> Box<dyn Future<Item = String, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/lol-league-session/v1/league-session-token".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

}
