/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct PluginLolServiceStatusApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> PluginLolServiceStatusApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> PluginLolServiceStatusApiClient<C> {
        PluginLolServiceStatusApiClient {
            configuration,
        }
    }
}

pub trait PluginLolServiceStatusApi {
    fn get_lol_service_status_v1_lcu_status(&self, ) -> Box<dyn Future<Item = crate::models::LolServiceStatusServiceStatusResource, Error = Error<serde_json::Value>>>;
    fn get_lol_service_status_v1_ticker_messages(&self, ) -> Box<dyn Future<Item = Vec<crate::models::LolServiceStatusTickerMessage>, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>PluginLolServiceStatusApi for PluginLolServiceStatusApiClient<C> {
    fn get_lol_service_status_v1_lcu_status(&self, ) -> Box<dyn Future<Item = crate::models::LolServiceStatusServiceStatusResource, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/lol-service-status/v1/lcu-status".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_lol_service_status_v1_ticker_messages(&self, ) -> Box<dyn Future<Item = Vec<crate::models::LolServiceStatusTickerMessage>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/lol-service-status/v1/ticker-messages".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

}
