/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct PluginLolRecommendationsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> PluginLolRecommendationsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> PluginLolRecommendationsApiClient<C> {
        PluginLolRecommendationsApiClient {
            configuration,
        }
    }
}

pub trait PluginLolRecommendationsApi {
    fn get_lol_recommendations_v1_recommendations(&self, number_of_recommendations: Option<i32>) -> Box<dyn Future<Item = crate::models::LolRecommendationsRecommendationsCollection, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>PluginLolRecommendationsApi for PluginLolRecommendationsApiClient<C> {
    fn get_lol_recommendations_v1_recommendations(&self, number_of_recommendations: Option<i32>) -> Box<dyn Future<Item = crate::models::LolRecommendationsRecommendationsCollection, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/lol-recommendations/v1/recommendations".to_string())
        ;
        if let Some(ref s) = number_of_recommendations {
            req = req.with_query_param("numberOfRecommendations".to_string(), s.to_string());
        }

        req.execute(self.configuration.borrow())
    }

}
