/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct SystemApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> SystemApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> SystemApiClient<C> {
        SystemApiClient {
            configuration,
        }
    }
}

pub trait SystemApi {
    fn get_system_v1_builds(&self, ) -> Box<dyn Future<Item = crate::models::BuildInfo, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>SystemApi for SystemApiClient<C> {
    fn get_system_v1_builds(&self, ) -> Box<dyn Future<Item = crate::models::BuildInfo, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/system/v1/builds".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

}
