/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BindingFullFieldHelp : Describes a member of a struct.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BindingFullFieldHelp {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::BindingFullTypeIdentifier>,
}

impl BindingFullFieldHelp {
    /// Describes a member of a struct.
    pub fn new() -> BindingFullFieldHelp {
        BindingFullFieldHelp {
            description: None,
            name: None,
            offset: None,
            optional: None,
            _type: None,
        }
    }
}


