/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BindingFullEventHelp : Describes an event.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BindingFullEventHelp {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nameSpace", skip_serializing_if = "Option::is_none")]
    pub name_space: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::BindingFullTypeIdentifier>,
}

impl BindingFullEventHelp {
    /// Describes an event.
    pub fn new() -> BindingFullEventHelp {
        BindingFullEventHelp {
            description: None,
            name: None,
            name_space: None,
            tags: None,
            _type: None,
        }
    }
}


