/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientConfigAuthenticatedConnection {
    #[serde(rename = "authToken", skip_serializing_if = "Option::is_none")]
    pub auth_token: Option<String>,
    #[serde(rename = "connectionId", skip_serializing_if = "Option::is_none")]
    pub connection_id: Option<i32>,
    #[serde(rename = "subscribed", skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<bool>,
}

impl ClientConfigAuthenticatedConnection {
    pub fn new() -> ClientConfigAuthenticatedConnection {
        ClientConfigAuthenticatedConnection {
            auth_token: None,
            connection_id: None,
            subscribed: None,
        }
    }
}


