/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientConfigDepInjectorEntitlementsUpdate {
    #[serde(rename = "EntitlementsTokenResource", skip_serializing_if = "Option::is_none")]
    pub entitlements_token_resource: Option<crate::models::ClientConfigDepInjectorEntitlements>,
    #[serde(rename = "EntitlementsUpdateType", skip_serializing_if = "Option::is_none")]
    pub entitlements_update_type: Option<crate::models::ClientConfigDepInjectorEntitlementsUpdateType>,
}

impl ClientConfigDepInjectorEntitlementsUpdate {
    pub fn new() -> ClientConfigDepInjectorEntitlementsUpdate {
        ClientConfigDepInjectorEntitlementsUpdate {
            entitlements_token_resource: None,
            entitlements_update_type: None,
        }
    }
}


