/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionsLcdsSummonerIconInventoryDto {
    #[serde(rename = "dateString", skip_serializing_if = "Option::is_none")]
    pub date_string: Option<String>,
    #[serde(rename = "summonerIcons", skip_serializing_if = "Option::is_none")]
    pub summoner_icons: Option<Vec<crate::models::CollectionsLcdsSummonerIcon>>,
    #[serde(rename = "summonerId", skip_serializing_if = "Option::is_none")]
    pub summoner_id: Option<i64>,
}

impl CollectionsLcdsSummonerIconInventoryDto {
    pub fn new() -> CollectionsLcdsSummonerIconInventoryDto {
        CollectionsLcdsSummonerIconInventoryDto {
            date_string: None,
            summoner_icons: None,
            summoner_id: None,
        }
    }
}


