/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraftLootRefTransactionDto {
    #[serde(rename = "lootNameRefIds", skip_serializing_if = "Option::is_none")]
    pub loot_name_ref_ids: Option<Vec<crate::models::LootNameRefId>>,
    #[serde(rename = "recipeName", skip_serializing_if = "Option::is_none")]
    pub recipe_name: Option<String>,
    #[serde(rename = "repeat", skip_serializing_if = "Option::is_none")]
    pub repeat: Option<i32>,
}

impl CraftLootRefTransactionDto {
    pub fn new() -> CraftLootRefTransactionDto {
        CraftLootRefTransactionDto {
            loot_name_ref_ids: None,
            recipe_name: None,
            repeat: None,
        }
    }
}


