/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndOfGameLcdsSpell {
    #[serde(rename = "spellId", skip_serializing_if = "Option::is_none")]
    pub spell_id: Option<i32>,
}

impl EndOfGameLcdsSpell {
    pub fn new() -> EndOfGameLcdsSpell {
        EndOfGameLcdsSpell {
            spell_id: None,
        }
    }
}


