/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LcdsInviteeState {
    #[serde(rename = "CREATOR")]
    CREATOR,
    #[serde(rename = "PENDING")]
    PENDING,
    #[serde(rename = "DECLINED")]
    DECLINED,
    #[serde(rename = "ACCEPTED")]
    ACCEPTED,
    #[serde(rename = "ACCEPT_FAILED")]
    ACCEPTFAILED,
    #[serde(rename = "JOINED")]
    JOINED,
    #[serde(rename = "QUIT")]
    QUIT,
    #[serde(rename = "KICKED")]
    KICKED,
    #[serde(rename = "BANNED")]
    BANNED,

}




