/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeagueEntryChangeEventDtov2 {
    #[serde(rename = "leagueItem", skip_serializing_if = "Option::is_none")]
    pub league_item: Option<crate::models::LeaguesLcdsLeagueItemDto>,
    #[serde(rename = "leaguePointsDelta", skip_serializing_if = "Option::is_none")]
    pub league_points_delta: Option<i32>,
    #[serde(rename = "lpChangeReason", skip_serializing_if = "Option::is_none")]
    pub lp_change_reason: Option<String>,
    #[serde(rename = "notifyReason", skip_serializing_if = "Option::is_none")]
    pub notify_reason: Option<String>,
}

impl LeagueEntryChangeEventDtov2 {
    pub fn new() -> LeagueEntryChangeEventDtov2 {
        LeagueEntryChangeEventDtov2 {
            league_item: None,
            league_points_delta: None,
            lp_change_reason: None,
            notify_reason: None,
        }
    }
}


