/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LolLobbyLobbyInvitationState {
    #[serde(rename = "Requested")]
    Requested,
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Accepted")]
    Accepted,
    #[serde(rename = "Joined")]
    Joined,
    #[serde(rename = "Declined")]
    Declined,
    #[serde(rename = "Kicked")]
    Kicked,
    #[serde(rename = "OnHold")]
    OnHold,
    #[serde(rename = "Error")]
    Error,

}




