/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolNpeRewardsMissionsRewardPackMetaData {
    #[serde(rename = "npeRewardPack", skip_serializing_if = "Option::is_none")]
    pub npe_reward_pack: Option<crate::models::LolNpeRewardsRewardPack>,
}

impl LolNpeRewardsMissionsRewardPackMetaData {
    pub fn new() -> LolNpeRewardsMissionsRewardPackMetaData {
        LolNpeRewardsMissionsRewardPackMetaData {
            npe_reward_pack: None,
        }
    }
}


