/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolHighlightsHighlightsConfig {
    #[serde(rename = "invalidHighlightNameCharacters", skip_serializing_if = "Option::is_none")]
    pub invalid_highlight_name_characters: Option<String>,
    #[serde(rename = "isHighlightsEnabled", skip_serializing_if = "Option::is_none")]
    pub is_highlights_enabled: Option<bool>,
}

impl LolHighlightsHighlightsConfig {
    pub fn new() -> LolHighlightsHighlightsConfig {
        LolHighlightsHighlightsConfig {
            invalid_highlight_name_characters: None,
            is_highlights_enabled: None,
        }
    }
}


