/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolRecommendationsCatalogItem {
    #[serde(rename = "inventoryType", skip_serializing_if = "Option::is_none")]
    pub inventory_type: Option<String>,
    #[serde(rename = "itemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i32>,
    #[serde(rename = "itemRequirements", skip_serializing_if = "Option::is_none")]
    pub item_requirements: Option<Vec<crate::models::LolRecommendationsItemKey>>,
    #[serde(rename = "maxQuantity", skip_serializing_if = "Option::is_none")]
    pub max_quantity: Option<i32>,
    #[serde(rename = "prices", skip_serializing_if = "Option::is_none")]
    pub prices: Option<Vec<crate::models::LolRecommendationsItemCost>>,
    #[serde(rename = "sale", skip_serializing_if = "Option::is_none")]
    pub sale: Option<crate::models::LolRecommendationsSale>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl LolRecommendationsCatalogItem {
    pub fn new() -> LolRecommendationsCatalogItem {
        LolRecommendationsCatalogItem {
            inventory_type: None,
            item_id: None,
            item_requirements: None,
            max_quantity: None,
            prices: None,
            sale: None,
            tags: None,
        }
    }
}


