/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChampSelectCollectionsChampionMinimal {
    #[serde(rename = "banVoPath", skip_serializing_if = "Option::is_none")]
    pub ban_vo_path: Option<String>,
    #[serde(rename = "chooseVoPath", skip_serializing_if = "Option::is_none")]
    pub choose_vo_path: Option<String>,
    #[serde(rename = "disabledQueues", skip_serializing_if = "Option::is_none")]
    pub disabled_queues: Option<Vec<String>>,
    #[serde(rename = "freeToPlay", skip_serializing_if = "Option::is_none")]
    pub free_to_play: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ownership", skip_serializing_if = "Option::is_none")]
    pub ownership: Option<crate::models::LolChampSelectCollectionsOwnership>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<String>>,
    #[serde(rename = "squarePortraitPath", skip_serializing_if = "Option::is_none")]
    pub square_portrait_path: Option<String>,
    #[serde(rename = "stingerSfxPath", skip_serializing_if = "Option::is_none")]
    pub stinger_sfx_path: Option<String>,
}

impl LolChampSelectCollectionsChampionMinimal {
    pub fn new() -> LolChampSelectCollectionsChampionMinimal {
        LolChampSelectCollectionsChampionMinimal {
            ban_vo_path: None,
            choose_vo_path: None,
            disabled_queues: None,
            free_to_play: None,
            id: None,
            name: None,
            ownership: None,
            roles: None,
            square_portrait_path: None,
            stinger_sfx_path: None,
        }
    }
}


