/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPerksServiceSettings {
    #[serde(rename = "serverSideStorageAvailable", skip_serializing_if = "Option::is_none")]
    pub server_side_storage_available: Option<bool>,
}

impl LolPerksServiceSettings {
    pub fn new() -> LolPerksServiceSettings {
        LolPerksServiceSettings {
            server_side_storage_available: None,
        }
    }
}


