/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChatFriendRequestAdd {
    #[serde(rename = "game_name", skip_serializing_if = "Option::is_none")]
    pub game_name: Option<String>,
    #[serde(rename = "game_tag", skip_serializing_if = "Option::is_none")]
    pub game_tag: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<String>,
    #[serde(rename = "puuid", skip_serializing_if = "Option::is_none")]
    pub puuid: Option<String>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

impl LolChatFriendRequestAdd {
    pub fn new() -> LolChatFriendRequestAdd {
        LolChatFriendRequestAdd {
            game_name: None,
            game_tag: None,
            name: None,
            note: None,
            pid: None,
            puuid: None,
            region: None,
        }
    }
}


