/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolRankedEosSettingsData {
    #[serde(rename = "notificationShown", skip_serializing_if = "Option::is_none")]
    pub notification_shown: Option<bool>,
}

impl LolRankedEosSettingsData {
    pub fn new() -> LolRankedEosSettingsData {
        LolRankedEosSettingsData {
            notification_shown: None,
        }
    }
}


