/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLoadoutsQueue {
    #[serde(rename = "isTeamBuilderManaged", skip_serializing_if = "Option::is_none")]
    pub is_team_builder_managed: Option<bool>,
}

impl LolLoadoutsQueue {
    pub fn new() -> LolLoadoutsQueue {
        LolLoadoutsQueue {
            is_team_builder_managed: None,
        }
    }
}


