/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolTrophiesClashV2TrophyRewardSpec {
    #[serde(rename = "bracket", skip_serializing_if = "Option::is_none")]
    pub bracket: Option<String>,
    #[serde(rename = "cup", skip_serializing_if = "Option::is_none")]
    pub cup: Option<String>,
    #[serde(rename = "gem", skip_serializing_if = "Option::is_none")]
    pub gem: Option<String>,
    #[serde(rename = "pedestal", skip_serializing_if = "Option::is_none")]
    pub pedestal: Option<String>,
    #[serde(rename = "seasonId", skip_serializing_if = "Option::is_none")]
    pub season_id: Option<String>,
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
}

impl LolTrophiesClashV2TrophyRewardSpec {
    pub fn new() -> LolTrophiesClashV2TrophyRewardSpec {
        LolTrophiesClashV2TrophyRewardSpec {
            bracket: None,
            cup: None,
            gem: None,
            pedestal: None,
            season_id: None,
            theme: None,
            tier: None,
        }
    }
}


