/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLobbyTeamBuilderChampionSelectPreferences {
    #[serde(rename = "skins", skip_serializing_if = "Option::is_none")]
    pub skins: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "spells", skip_serializing_if = "Option::is_none")]
    pub spells: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, serde_json::Value>>>,
}

impl LolLobbyTeamBuilderChampionSelectPreferences {
    pub fn new() -> LolLobbyTeamBuilderChampionSelectPreferences {
        LolLobbyTeamBuilderChampionSelectPreferences {
            skins: None,
            spells: None,
        }
    }
}


