/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLootPlayerLootMap {
    #[serde(rename = "playerLoot", skip_serializing_if = "Option::is_none")]
    pub player_loot: Option<::std::collections::HashMap<String, crate::models::LolLootPlayerLoot>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

impl LolLootPlayerLootMap {
    pub fn new() -> LolLootPlayerLootMap {
        LolLootPlayerLootMap {
            player_loot: None,
            version: None,
        }
    }
}


