/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolStoreBundled {
    #[serde(rename = "flexible", skip_serializing_if = "Option::is_none")]
    pub flexible: Option<bool>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::LolStoreBundledItem>>,
    #[serde(rename = "minimumPrices", skip_serializing_if = "Option::is_none")]
    pub minimum_prices: Option<Vec<crate::models::LolStoreBundledItemCost>>,
}

impl LolStoreBundled {
    pub fn new() -> LolStoreBundled {
        LolStoreBundled {
            flexible: None,
            items: None,
            minimum_prices: None,
        }
    }
}


