/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolStoreGiftingConfig {
    #[serde(rename = "giftingHextecMaxDailyGiftsReceive", skip_serializing_if = "Option::is_none")]
    pub gifting_hextec_max_daily_gifts_receive: Option<i32>,
    #[serde(rename = "giftingHextechMaxDailyGiftsSend", skip_serializing_if = "Option::is_none")]
    pub gifting_hextech_max_daily_gifts_send: Option<i32>,
    #[serde(rename = "giftingItemMaxDailyGiftsReceive", skip_serializing_if = "Option::is_none")]
    pub gifting_item_max_daily_gifts_receive: Option<i32>,
    #[serde(rename = "giftingItemMaxDailyGiftsSend", skip_serializing_if = "Option::is_none")]
    pub gifting_item_max_daily_gifts_send: Option<i32>,
    #[serde(rename = "giftingItemMinLevelSend", skip_serializing_if = "Option::is_none")]
    pub gifting_item_min_level_send: Option<i32>,
    #[serde(rename = "giftingRestrictionFlagRioter", skip_serializing_if = "Option::is_none")]
    pub gifting_restriction_flag_rioter: Option<i32>,
    #[serde(rename = "giftingRpMaxDailyGiftsReceive", skip_serializing_if = "Option::is_none")]
    pub gifting_rp_max_daily_gifts_receive: Option<i32>,
    #[serde(rename = "giftingRpMaxDailyGiftsSend", skip_serializing_if = "Option::is_none")]
    pub gifting_rp_max_daily_gifts_send: Option<i32>,
    #[serde(rename = "giftingRpMinLevelSend", skip_serializing_if = "Option::is_none")]
    pub gifting_rp_min_level_send: Option<i32>,
    #[serde(rename = "recipientLevelLimitItem", skip_serializing_if = "Option::is_none")]
    pub recipient_level_limit_item: Option<i32>,
    #[serde(rename = "recipientLevelLimitRp", skip_serializing_if = "Option::is_none")]
    pub recipient_level_limit_rp: Option<i32>,
    #[serde(rename = "requiresIdentityVerification", skip_serializing_if = "Option::is_none")]
    pub requires_identity_verification: Option<bool>,
}

impl LolStoreGiftingConfig {
    pub fn new() -> LolStoreGiftingConfig {
        LolStoreGiftingConfig {
            gifting_hextec_max_daily_gifts_receive: None,
            gifting_hextech_max_daily_gifts_send: None,
            gifting_item_max_daily_gifts_receive: None,
            gifting_item_max_daily_gifts_send: None,
            gifting_item_min_level_send: None,
            gifting_restriction_flag_rioter: None,
            gifting_rp_max_daily_gifts_receive: None,
            gifting_rp_max_daily_gifts_send: None,
            gifting_rp_min_level_send: None,
            recipient_level_limit_item: None,
            recipient_level_limit_rp: None,
            requires_identity_verification: None,
        }
    }
}


