/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChampSelectChampGridChampion {
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    #[serde(rename = "freeToPlay", skip_serializing_if = "Option::is_none")]
    pub free_to_play: Option<bool>,
    #[serde(rename = "freeToPlayForQueue", skip_serializing_if = "Option::is_none")]
    pub free_to_play_for_queue: Option<bool>,
    #[serde(rename = "freeToPlayReward", skip_serializing_if = "Option::is_none")]
    pub free_to_play_reward: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "masteryChestGranted", skip_serializing_if = "Option::is_none")]
    pub mastery_chest_granted: Option<bool>,
    #[serde(rename = "masteryLevel", skip_serializing_if = "Option::is_none")]
    pub mastery_level: Option<i32>,
    #[serde(rename = "masteryPoints", skip_serializing_if = "Option::is_none")]
    pub mastery_points: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "owned", skip_serializing_if = "Option::is_none")]
    pub owned: Option<bool>,
    #[serde(rename = "positionsFavorited", skip_serializing_if = "Option::is_none")]
    pub positions_favorited: Option<Vec<String>>,
    #[serde(rename = "rented", skip_serializing_if = "Option::is_none")]
    pub rented: Option<bool>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<String>>,
    #[serde(rename = "selectionStatus", skip_serializing_if = "Option::is_none")]
    pub selection_status: Option<crate::models::LolChampSelectChampionSelection>,
    #[serde(rename = "squarePortraitPath", skip_serializing_if = "Option::is_none")]
    pub square_portrait_path: Option<String>,
}

impl LolChampSelectChampGridChampion {
    pub fn new() -> LolChampSelectChampGridChampion {
        LolChampSelectChampGridChampion {
            disabled: None,
            free_to_play: None,
            free_to_play_for_queue: None,
            free_to_play_reward: None,
            id: None,
            mastery_chest_granted: None,
            mastery_level: None,
            mastery_points: None,
            name: None,
            owned: None,
            positions_favorited: None,
            rented: None,
            roles: None,
            selection_status: None,
            square_portrait_path: None,
        }
    }
}


