/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolContentTargetingSummoner {
    #[serde(rename = "profileIconId", skip_serializing_if = "Option::is_none")]
    pub profile_icon_id: Option<i32>,
    #[serde(rename = "summonerLevel", skip_serializing_if = "Option::is_none")]
    pub summoner_level: Option<i32>,
}

impl LolContentTargetingSummoner {
    pub fn new() -> LolContentTargetingSummoner {
        LolContentTargetingSummoner {
            profile_icon_id: None,
            summoner_level: None,
        }
    }
}


