/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLobbyLobbyPartyRewards {
    #[serde(rename = "isCustom", skip_serializing_if = "Option::is_none")]
    pub is_custom: Option<bool>,
    #[serde(rename = "isEnabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    #[serde(rename = "partyRewards", skip_serializing_if = "Option::is_none")]
    pub party_rewards: Option<Vec<crate::models::LolLobbyPartyReward>>,
    #[serde(rename = "queueId", skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<i32>,
}

impl LolLobbyLobbyPartyRewards {
    pub fn new() -> LolLobbyLobbyPartyRewards {
        LolLobbyLobbyPartyRewards {
            is_custom: None,
            is_enabled: None,
            party_rewards: None,
            queue_id: None,
        }
    }
}


