/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolGameQueuesQueueCustomGame {
    #[serde(rename = "gameServerRegions", skip_serializing_if = "Option::is_none")]
    pub game_server_regions: Option<Vec<String>>,
    #[serde(rename = "queueAvailability", skip_serializing_if = "Option::is_none")]
    pub queue_availability: Option<crate::models::LolGameQueuesQueueAvailability>,
    #[serde(rename = "spectatorPolicies", skip_serializing_if = "Option::is_none")]
    pub spectator_policies: Option<Vec<crate::models::LolGameQueuesQueueCustomGameSpectatorPolicy>>,
    #[serde(rename = "spectatorSlotLimit", skip_serializing_if = "Option::is_none")]
    pub spectator_slot_limit: Option<i32>,
    #[serde(rename = "subcategories", skip_serializing_if = "Option::is_none")]
    pub subcategories: Option<Vec<crate::models::LolGameQueuesQueueCustomGameSubcategory>>,
}

impl LolGameQueuesQueueCustomGame {
    pub fn new() -> LolGameQueuesQueueCustomGame {
        LolGameQueuesQueueCustomGame {
            game_server_regions: None,
            queue_availability: None,
            spectator_policies: None,
            spectator_slot_limit: None,
            subcategories: None,
        }
    }
}


