/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLoadoutsGameflowGameData {
    #[serde(rename = "queue", skip_serializing_if = "Option::is_none")]
    pub queue: Option<crate::models::LolLoadoutsQueue>,
}

impl LolLoadoutsGameflowGameData {
    pub fn new() -> LolLoadoutsGameflowGameData {
        LolLoadoutsGameflowGameData {
            queue: None,
        }
    }
}


