/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolStatstonesEogNotificationEnvelope {
    #[serde(rename = "othersPersonalBests", skip_serializing_if = "Option::is_none")]
    pub others_personal_bests: Option<Vec<crate::models::LolStatstonesPersonalBestNotification>>,
    #[serde(rename = "selfMilestoneProgress", skip_serializing_if = "Option::is_none")]
    pub self_milestone_progress: Option<Vec<crate::models::LolStatstonesMilestoneProgressNotification>>,
    #[serde(rename = "selfPersonalBests", skip_serializing_if = "Option::is_none")]
    pub self_personal_bests: Option<Vec<crate::models::LolStatstonesPersonalBestNotification>>,
    #[serde(rename = "selfStatstoneProgress", skip_serializing_if = "Option::is_none")]
    pub self_statstone_progress: Option<Vec<crate::models::LolStatstonesStatstoneProgress>>,
}

impl LolStatstonesEogNotificationEnvelope {
    pub fn new() -> LolStatstonesEogNotificationEnvelope {
        LolStatstonesEogNotificationEnvelope {
            others_personal_bests: None,
            self_milestone_progress: None,
            self_personal_bests: None,
            self_statstone_progress: None,
        }
    }
}


