/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolAcsAcsEndPoint {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl LolAcsAcsEndPoint {
    pub fn new() -> LolAcsAcsEndPoint {
        LolAcsAcsEndPoint {
            url: None,
        }
    }
}


