/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolMatchHistoryMatchHistoryParticipantIdentityPlayer {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i64>,
    #[serde(rename = "currentAccountId", skip_serializing_if = "Option::is_none")]
    pub current_account_id: Option<i64>,
    #[serde(rename = "currentPlatformId", skip_serializing_if = "Option::is_none")]
    pub current_platform_id: Option<String>,
    #[serde(rename = "matchHistoryUri", skip_serializing_if = "Option::is_none")]
    pub match_history_uri: Option<String>,
    #[serde(rename = "platformId", skip_serializing_if = "Option::is_none")]
    pub platform_id: Option<String>,
    #[serde(rename = "profileIcon", skip_serializing_if = "Option::is_none")]
    pub profile_icon: Option<i32>,
    #[serde(rename = "summonerId", skip_serializing_if = "Option::is_none")]
    pub summoner_id: Option<i64>,
    #[serde(rename = "summonerName", skip_serializing_if = "Option::is_none")]
    pub summoner_name: Option<String>,
}

impl LolMatchHistoryMatchHistoryParticipantIdentityPlayer {
    pub fn new() -> LolMatchHistoryMatchHistoryParticipantIdentityPlayer {
        LolMatchHistoryMatchHistoryParticipantIdentityPlayer {
            account_id: None,
            current_account_id: None,
            current_platform_id: None,
            match_history_uri: None,
            platform_id: None,
            profile_icon: None,
            summoner_id: None,
            summoner_name: None,
        }
    }
}


