/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolCareerStatsChampionQueueStatsResponse {
    #[serde(rename = "championId", skip_serializing_if = "Option::is_none")]
    pub champion_id: Option<i32>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<crate::models::LolCareerStatsSummonersRiftPosition>,
    #[serde(rename = "queueType", skip_serializing_if = "Option::is_none")]
    pub queue_type: Option<crate::models::LolCareerStatsCareerStatsQueueType>,
    #[serde(rename = "rankTier", skip_serializing_if = "Option::is_none")]
    pub rank_tier: Option<crate::models::LolCareerStatsRankedTier>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl LolCareerStatsChampionQueueStatsResponse {
    pub fn new() -> LolCareerStatsChampionQueueStatsResponse {
        LolCareerStatsChampionQueueStatsResponse {
            champion_id: None,
            position: None,
            queue_type: None,
            rank_tier: None,
            stats: None,
        }
    }
}


