/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LolRecommendationsItemType {
    #[serde(rename = "CHAMPION")]
    CHAMPION,
    #[serde(rename = "CHAMPION_SKIN")]
    CHAMPIONSKIN,
    #[serde(rename = "BUNDLES")]
    BUNDLES,
    #[serde(rename = "HEXTECH_CRAFTING")]
    HEXTECHCRAFTING,
    #[serde(rename = "SUMMONER_ICON")]
    SUMMONERICON,
    #[serde(rename = "WARD_SKIN")]
    WARDSKIN,
    #[serde(rename = "EMOTE")]
    EMOTE,

}




