/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPatchPatcherSelfUpdateSettings {
    #[serde(rename = "restart_delay", skip_serializing_if = "Option::is_none")]
    pub restart_delay: Option<i32>,
}

impl LolPatchPatcherSelfUpdateSettings {
    pub fn new() -> LolPatchPatcherSelfUpdateSettings {
        LolPatchPatcherSelfUpdateSettings {
            restart_delay: None,
        }
    }
}


