/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLootRecipe {
    #[serde(rename = "contextMenuText", skip_serializing_if = "Option::is_none")]
    pub context_menu_text: Option<String>,
    #[serde(rename = "crafterName", skip_serializing_if = "Option::is_none")]
    pub crafter_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "displayCategories", skip_serializing_if = "Option::is_none")]
    pub display_categories: Option<String>,
    #[serde(rename = "imagePath", skip_serializing_if = "Option::is_none")]
    pub image_path: Option<String>,
    #[serde(rename = "introVideoPath", skip_serializing_if = "Option::is_none")]
    pub intro_video_path: Option<String>,
    #[serde(rename = "loopVideoPath", skip_serializing_if = "Option::is_none")]
    pub loop_video_path: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::models::LolLootRecipeMetadata>,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<crate::models::LolLootRecipeOutput>>,
    #[serde(rename = "outroVideoPath", skip_serializing_if = "Option::is_none")]
    pub outro_video_path: Option<String>,
    #[serde(rename = "recipeName", skip_serializing_if = "Option::is_none")]
    pub recipe_name: Option<String>,
    #[serde(rename = "requirementText", skip_serializing_if = "Option::is_none")]
    pub requirement_text: Option<String>,
    #[serde(rename = "slots", skip_serializing_if = "Option::is_none")]
    pub slots: Option<Vec<crate::models::LolLootRecipeSlot>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl LolLootRecipe {
    pub fn new() -> LolLootRecipe {
        LolLootRecipe {
            context_menu_text: None,
            crafter_name: None,
            description: None,
            display_categories: None,
            image_path: None,
            intro_video_path: None,
            loop_video_path: None,
            metadata: None,
            outputs: None,
            outro_video_path: None,
            recipe_name: None,
            requirement_text: None,
            slots: None,
            _type: None,
        }
    }
}


