/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolRegaliaRegaliaSettings {
    #[serde(rename = "bannerType", skip_serializing_if = "Option::is_none")]
    pub banner_type: Option<crate::models::LolRegaliaRegaliaBannerType>,
    #[serde(rename = "crestType", skip_serializing_if = "Option::is_none")]
    pub crest_type: Option<crate::models::LolRegaliaRegaliaCrestType>,
}

impl LolRegaliaRegaliaSettings {
    pub fn new() -> LolRegaliaRegaliaSettings {
        LolRegaliaRegaliaSettings {
            banner_type: None,
            crest_type: None,
        }
    }
}


