/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClashPlayerChatRoster {
    #[serde(rename = "endTimeMs", skip_serializing_if = "Option::is_none")]
    pub end_time_ms: Option<i64>,
    #[serde(rename = "iconColorId", skip_serializing_if = "Option::is_none")]
    pub icon_color_id: Option<i32>,
    #[serde(rename = "iconId", skip_serializing_if = "Option::is_none")]
    pub icon_id: Option<i32>,
    #[serde(rename = "invitationId", skip_serializing_if = "Option::is_none")]
    pub invitation_id: Option<String>,
    #[serde(rename = "isRegistered", skip_serializing_if = "Option::is_none")]
    pub is_registered: Option<bool>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "logoUrl", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "playerState", skip_serializing_if = "Option::is_none")]
    pub player_state: Option<crate::models::LolClashPlayerState>,
    #[serde(rename = "shortName", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<String>,
    #[serde(rename = "startTimeMs", skip_serializing_if = "Option::is_none")]
    pub start_time_ms: Option<i64>,
    #[serde(rename = "tournamentId", skip_serializing_if = "Option::is_none")]
    pub tournament_id: Option<i64>,
    #[serde(rename = "tournamentState", skip_serializing_if = "Option::is_none")]
    pub tournament_state: Option<crate::models::LolClashTournamentState>,
}

impl LolClashPlayerChatRoster {
    pub fn new() -> LolClashPlayerChatRoster {
        LolClashPlayerChatRoster {
            end_time_ms: None,
            icon_color_id: None,
            icon_id: None,
            invitation_id: None,
            is_registered: None,
            key: None,
            logo_url: None,
            name: None,
            player_state: None,
            short_name: None,
            start_time_ms: None,
            tournament_id: None,
            tournament_state: None,
        }
    }
}


