/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLoyaltyLoyaltyRewards {
    #[serde(rename = "championIds", skip_serializing_if = "Option::is_none")]
    pub champion_ids: Option<Vec<i32>>,
    #[serde(rename = "freeRewardedChampionsCount", skip_serializing_if = "Option::is_none")]
    pub free_rewarded_champions_count: Option<i32>,
    #[serde(rename = "freeRewardedSkinsCount", skip_serializing_if = "Option::is_none")]
    pub free_rewarded_skins_count: Option<i32>,
    #[serde(rename = "global", skip_serializing_if = "Option::is_none")]
    pub global: Option<crate::models::LolLoyaltyGlobalRewards>,
    #[serde(rename = "ipBoost", skip_serializing_if = "Option::is_none")]
    pub ip_boost: Option<i32>,
    #[serde(rename = "loyaltyTFTCompanionCount", skip_serializing_if = "Option::is_none")]
    pub loyalty_tft_companion_count: Option<i32>,
    #[serde(rename = "loyaltyTFTMapSkinCount", skip_serializing_if = "Option::is_none")]
    pub loyalty_tft_map_skin_count: Option<i32>,
    #[serde(rename = "skinIds", skip_serializing_if = "Option::is_none")]
    pub skin_ids: Option<Vec<i32>>,
    #[serde(rename = "xpBoost", skip_serializing_if = "Option::is_none")]
    pub xp_boost: Option<i32>,
}

impl LolLoyaltyLoyaltyRewards {
    pub fn new() -> LolLoyaltyLoyaltyRewards {
        LolLoyaltyLoyaltyRewards {
            champion_ids: None,
            free_rewarded_champions_count: None,
            free_rewarded_skins_count: None,
            global: None,
            ip_boost: None,
            loyalty_tft_companion_count: None,
            loyalty_tft_map_skin_count: None,
            skin_ids: None,
            xp_boost: None,
        }
    }
}


