/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolKrShutdownLawAntiAddictionState {
    #[serde(rename = "policyType", skip_serializing_if = "Option::is_none")]
    pub policy_type: Option<crate::models::LolKrShutdownLawPolicyType>,
}

impl LolKrShutdownLawAntiAddictionState {
    pub fn new() -> LolKrShutdownLawAntiAddictionState {
        LolKrShutdownLawAntiAddictionState {
            policy_type: None,
        }
    }
}


