/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClubsClubDto {
    #[serde(rename = "clubData", skip_serializing_if = "Option::is_none")]
    pub club_data: Option<crate::models::LolClubsClubDataDto>,
    #[serde(rename = "membership", skip_serializing_if = "Option::is_none")]
    pub membership: Option<crate::models::LolClubsClubMembershipDto>,
    #[serde(rename = "platformId", skip_serializing_if = "Option::is_none")]
    pub platform_id: Option<String>,
    #[serde(rename = "resourceUri", skip_serializing_if = "Option::is_none")]
    pub resource_uri: Option<String>,
}

impl LolClubsClubDto {
    pub fn new() -> LolClubsClubDto {
        LolClubsClubDto {
            club_data: None,
            membership: None,
            platform_id: None,
            resource_uri: None,
        }
    }
}


