/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChampSelectLegacyQueue {
    #[serde(rename = "areFreeChampionsAllowed", skip_serializing_if = "Option::is_none")]
    pub are_free_champions_allowed: Option<bool>,
    #[serde(rename = "gameTypeConfig", skip_serializing_if = "Option::is_none")]
    pub game_type_config: Option<crate::models::LolChampSelectLegacyQueueGameTypeConfig>,
}

impl LolChampSelectLegacyQueue {
    pub fn new() -> LolChampSelectLegacyQueue {
        LolChampSelectLegacyQueue {
            are_free_champions_allowed: None,
            game_type_config: None,
        }
    }
}


