/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPremadeVoiceGameEventHotkeys {
    #[serde(rename = "evtPushToTalk", skip_serializing_if = "Option::is_none")]
    pub evt_push_to_talk: Option<String>,
}

impl LolPremadeVoiceGameEventHotkeys {
    pub fn new() -> LolPremadeVoiceGameEventHotkeys {
        LolPremadeVoiceGameEventHotkeys {
            evt_push_to_talk: None,
        }
    }
}


