/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClashTournamentHistoryAndWinners {
    #[serde(rename = "tournamentHistory", skip_serializing_if = "Option::is_none")]
    pub tournament_history: Option<Vec<crate::models::LolClashTournament>>,
    #[serde(rename = "tournamentWinners", skip_serializing_if = "Option::is_none")]
    pub tournament_winners: Option<crate::models::LolClashTournamentWinnerHistory>,
}

impl LolClashTournamentHistoryAndWinners {
    pub fn new() -> LolClashTournamentHistoryAndWinners {
        LolClashTournamentHistoryAndWinners {
            tournament_history: None,
            tournament_winners: None,
        }
    }
}


