/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChatChatServiceDynamicClientConfig {
    #[serde(rename = "ChatDomain", skip_serializing_if = "Option::is_none")]
    pub chat_domain: Option<crate::models::LolChatChatDomainConfig>,
    #[serde(rename = "LcuSocial", skip_serializing_if = "Option::is_none")]
    pub lcu_social: Option<crate::models::LolChatLcuSocialConfig>,
}

impl LolChatChatServiceDynamicClientConfig {
    pub fn new() -> LolChatChatServiceDynamicClientConfig {
        LolChatChatServiceDynamicClientConfig {
            chat_domain: None,
            lcu_social: None,
        }
    }
}


