/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LolClashTournamentNotifyReason {
    #[serde(rename = "NEW_TOURNAMENT")]
    NEWTOURNAMENT,
    #[serde(rename = "UPDATE_TOURNAMENT")]
    UPDATETOURNAMENT,
    #[serde(rename = "CANCEL_TOURNAMENT")]
    CANCELTOURNAMENT,
    #[serde(rename = "CANCEL_PERIOD")]
    CANCELPERIOD,
    #[serde(rename = "ADD_PHASE")]
    ADDPHASE,
    #[serde(rename = "UPDATE_PHASE")]
    UPDATEPHASE,
    #[serde(rename = "REVERT_PHASE")]
    REVERTPHASE,
    #[serde(rename = "UPDATE_STATUS")]
    UPDATESTATUS,

}




