/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClubsPlayerMembershipWithNotificationsDto {
    #[serde(rename = "membershipNotifications", skip_serializing_if = "Option::is_none")]
    pub membership_notifications: Option<Vec<crate::models::LolClubsMembershipNoficationsDto>>,
    #[serde(rename = "playerMembership", skip_serializing_if = "Option::is_none")]
    pub player_membership: Option<crate::models::LolClubsPlayerMembershipDto>,
}

impl LolClubsPlayerMembershipWithNotificationsDto {
    pub fn new() -> LolClubsPlayerMembershipWithNotificationsDto {
        LolClubsPlayerMembershipWithNotificationsDto {
            membership_notifications: None,
            player_membership: None,
        }
    }
}


