/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolEndOfGameGameflowSession {
    #[serde(rename = "gameClient", skip_serializing_if = "Option::is_none")]
    pub game_client: Option<crate::models::LolEndOfGameGameflowClient>,
    #[serde(rename = "gameData", skip_serializing_if = "Option::is_none")]
    pub game_data: Option<crate::models::LolEndOfGameGameflowGameData>,
    #[serde(rename = "phase", skip_serializing_if = "Option::is_none")]
    pub phase: Option<crate::models::LolEndOfGameGameflowPhase>,
}

impl LolEndOfGameGameflowSession {
    pub fn new() -> LolEndOfGameGameflowSession {
        LolEndOfGameGameflowSession {
            game_client: None,
            game_data: None,
            phase: None,
        }
    }
}


