/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolInventoryInventoryCacheEntry {
    #[serde(rename = "expirationMS", skip_serializing_if = "Option::is_none")]
    pub expiration_ms: Option<i64>,
    #[serde(rename = "issuedAtMS", skip_serializing_if = "Option::is_none")]
    pub issued_at_ms: Option<i64>,
    #[serde(rename = "receivedAtMS", skip_serializing_if = "Option::is_none")]
    pub received_at_ms: Option<i64>,
    #[serde(rename = "signedInventoryJwt", skip_serializing_if = "Option::is_none")]
    pub signed_inventory_jwt: Option<String>,
    #[serde(rename = "valid", skip_serializing_if = "Option::is_none")]
    pub valid: Option<bool>,
}

impl LolInventoryInventoryCacheEntry {
    pub fn new() -> LolInventoryInventoryCacheEntry {
        LolInventoryInventoryCacheEntry {
            expiration_ms: None,
            issued_at_ms: None,
            received_at_ms: None,
            signed_inventory_jwt: None,
            valid: None,
        }
    }
}


