/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolStatstonesChampionStatstoneSetSummary {
    #[serde(rename = "milestonesPassed", skip_serializing_if = "Option::is_none")]
    pub milestones_passed: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "stonesAvailable", skip_serializing_if = "Option::is_none")]
    pub stones_available: Option<i32>,
    #[serde(rename = "stonesIlluminated", skip_serializing_if = "Option::is_none")]
    pub stones_illuminated: Option<i32>,
    #[serde(rename = "stonesOwned", skip_serializing_if = "Option::is_none")]
    pub stones_owned: Option<i32>,
}

impl LolStatstonesChampionStatstoneSetSummary {
    pub fn new() -> LolStatstonesChampionStatstoneSetSummary {
        LolStatstonesChampionStatstoneSetSummary {
            milestones_passed: None,
            name: None,
            stones_available: None,
            stones_illuminated: None,
            stones_owned: None,
        }
    }
}


