/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolBannersCapClashFlagEntitlementPayload {
    #[serde(rename = "rewardSpec", skip_serializing_if = "Option::is_none")]
    pub reward_spec: Option<crate::models::LolBannersClashV2FlagRewardSpec>,
    #[serde(rename = "rewardType", skip_serializing_if = "Option::is_none")]
    pub reward_type: Option<String>,
}

impl LolBannersCapClashFlagEntitlementPayload {
    pub fn new() -> LolBannersCapClashFlagEntitlementPayload {
        LolBannersCapClashFlagEntitlementPayload {
            reward_spec: None,
            reward_type: None,
        }
    }
}


