/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPerksPerkUiStyle {
    #[serde(rename = "allowedSubStyles", skip_serializing_if = "Option::is_none")]
    pub allowed_sub_styles: Option<Vec<i32>>,
    #[serde(rename = "assetMap", skip_serializing_if = "Option::is_none")]
    pub asset_map: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "defaultPageName", skip_serializing_if = "Option::is_none")]
    pub default_page_name: Option<String>,
    #[serde(rename = "defaultPerks", skip_serializing_if = "Option::is_none")]
    pub default_perks: Option<Vec<i32>>,
    #[serde(rename = "defaultSubStyle", skip_serializing_if = "Option::is_none")]
    pub default_sub_style: Option<i32>,
    #[serde(rename = "iconPath", skip_serializing_if = "Option::is_none")]
    pub icon_path: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "slots", skip_serializing_if = "Option::is_none")]
    pub slots: Option<Vec<crate::models::LolPerksPerkUiSlot>>,
    #[serde(rename = "subStyleBonus", skip_serializing_if = "Option::is_none")]
    pub sub_style_bonus: Option<Vec<crate::models::LolPerksPerkSubStyleBonusResource>>,
    #[serde(rename = "tooltip", skip_serializing_if = "Option::is_none")]
    pub tooltip: Option<String>,
}

impl LolPerksPerkUiStyle {
    pub fn new() -> LolPerksPerkUiStyle {
        LolPerksPerkUiStyle {
            allowed_sub_styles: None,
            asset_map: None,
            default_page_name: None,
            default_perks: None,
            default_sub_style: None,
            icon_path: None,
            id: None,
            name: None,
            slots: None,
            sub_style_bonus: None,
            tooltip: None,
        }
    }
}


