/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClashPlayerUpdateNotification {
    #[serde(rename = "notifyReason", skip_serializing_if = "Option::is_none")]
    pub notify_reason: Option<crate::models::LolClashNotifyReason>,
    #[serde(rename = "player", skip_serializing_if = "Option::is_none")]
    pub player: Option<crate::models::PlayerDto>,
}

impl LolClashPlayerUpdateNotification {
    pub fn new() -> LolClashPlayerUpdateNotification {
        LolClashPlayerUpdateNotification {
            notify_reason: None,
            player: None,
        }
    }
}


