/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolHonorV2VendedReward {
    #[serde(rename = "dynamicHonorMessage", skip_serializing_if = "Option::is_none")]
    pub dynamic_honor_message: Option<crate::models::LolHonorV2DynamicHonorMessage>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
    #[serde(rename = "rewardType", skip_serializing_if = "Option::is_none")]
    pub reward_type: Option<String>,
}

impl LolHonorV2VendedReward {
    pub fn new() -> LolHonorV2VendedReward {
        LolHonorV2VendedReward {
            dynamic_honor_message: None,
            quantity: None,
            reward_type: None,
        }
    }
}


