/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLobbyCustomEligibilityDto {
    #[serde(rename = "eligible", skip_serializing_if = "Option::is_none")]
    pub eligible: Option<bool>,
    #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
    pub restrictions: Option<Vec<crate::models::LolLobbyGatekeeperRestrictionDto>>,
}

impl LolLobbyCustomEligibilityDto {
    pub fn new() -> LolLobbyCustomEligibilityDto {
        LolLobbyCustomEligibilityDto {
            eligible: None,
            restrictions: None,
        }
    }
}


