/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLoadoutsGetItemsRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "inventoryJWTs", skip_serializing_if = "Option::is_none")]
    pub inventory_jw_ts: Option<Vec<String>>,
    #[serde(rename = "inventoryTypes", skip_serializing_if = "Option::is_none")]
    pub inventory_types: Option<Vec<String>>,
}

impl LolLoadoutsGetItemsRequest {
    pub fn new() -> LolLoadoutsGetItemsRequest {
        LolLoadoutsGetItemsRequest {
            id: None,
            inventory_jw_ts: None,
            inventory_types: None,
        }
    }
}


