/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolInventoryWalletDto {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i64>,
    #[serde(rename = "balances", skip_serializing_if = "Option::is_none")]
    pub balances: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "balancesJwt", skip_serializing_if = "Option::is_none")]
    pub balances_jwt: Option<String>,
    #[serde(rename = "expires", skip_serializing_if = "Option::is_none")]
    pub expires: Option<String>,
    #[serde(rename = "puuid", skip_serializing_if = "Option::is_none")]
    pub puuid: Option<String>,
}

impl LolInventoryWalletDto {
    pub fn new() -> LolInventoryWalletDto {
        LolInventoryWalletDto {
            account_id: None,
            balances: None,
            balances_jwt: None,
            expires: None,
            puuid: None,
        }
    }
}


