/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolRankedLeagueLadderInfo {
    #[serde(rename = "divisions", skip_serializing_if = "Option::is_none")]
    pub divisions: Option<Vec<crate::models::LolRankedLeagueDivisionInfo>>,
    #[serde(rename = "nextApexUpdateMillis", skip_serializing_if = "Option::is_none")]
    pub next_apex_update_millis: Option<i64>,
    #[serde(rename = "provisionalGameThreshold", skip_serializing_if = "Option::is_none")]
    pub provisional_game_threshold: Option<i32>,
    #[serde(rename = "queueType", skip_serializing_if = "Option::is_none")]
    pub queue_type: Option<crate::models::LolRankedLeagueQueueType>,
    #[serde(rename = "requestedRankedEntry", skip_serializing_if = "Option::is_none")]
    pub requested_ranked_entry: Option<crate::models::LolRankedLeagueStanding>,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<crate::models::LolRankedLeagueTier>,
}

impl LolRankedLeagueLadderInfo {
    pub fn new() -> LolRankedLeagueLadderInfo {
        LolRankedLeagueLadderInfo {
            divisions: None,
            next_apex_update_millis: None,
            provisional_game_threshold: None,
            queue_type: None,
            requested_ranked_entry: None,
            tier: None,
        }
    }
}


