/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLoyaltyInventoryItemDto {
    #[serde(rename = "inventoryType", skip_serializing_if = "Option::is_none")]
    pub inventory_type: Option<String>,
    #[serde(rename = "loyalty", skip_serializing_if = "Option::is_none")]
    pub loyalty: Option<bool>,
}

impl LolLoyaltyInventoryItemDto {
    pub fn new() -> LolLoyaltyInventoryItemDto {
        LolLoyaltyInventoryItemDto {
            inventory_type: None,
            loyalty: None,
        }
    }
}


