/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClashScoutingChampionMastery {
    #[serde(rename = "championId", skip_serializing_if = "Option::is_none")]
    pub champion_id: Option<i32>,
    #[serde(rename = "championLevel", skip_serializing_if = "Option::is_none")]
    pub champion_level: Option<i32>,
    #[serde(rename = "championPoints", skip_serializing_if = "Option::is_none")]
    pub champion_points: Option<i32>,
}

impl LolClashScoutingChampionMastery {
    pub fn new() -> LolClashScoutingChampionMastery {
        LolClashScoutingChampionMastery {
            champion_id: None,
            champion_level: None,
            champion_points: None,
        }
    }
}


