/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolFeaturedModesEligibilityRestriction {
    #[serde(rename = "expiredTimestamp", skip_serializing_if = "Option::is_none")]
    pub expired_timestamp: Option<i64>,
    #[serde(rename = "restrictionArgs", skip_serializing_if = "Option::is_none")]
    pub restriction_args: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "restrictionCode", skip_serializing_if = "Option::is_none")]
    pub restriction_code: Option<crate::models::LolFeaturedModesEligibilityRestrictionCode>,
    #[serde(rename = "summonerIds", skip_serializing_if = "Option::is_none")]
    pub summoner_ids: Option<Vec<i64>>,
}

impl LolFeaturedModesEligibilityRestriction {
    pub fn new() -> LolFeaturedModesEligibilityRestriction {
        LolFeaturedModesEligibilityRestriction {
            expired_timestamp: None,
            restriction_args: None,
            restriction_code: None,
            summoner_ids: None,
        }
    }
}


