/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChampSelectLegacyQueueGameTypeConfig {
    #[serde(rename = "allowTrades", skip_serializing_if = "Option::is_none")]
    pub allow_trades: Option<bool>,
    #[serde(rename = "battleBoost", skip_serializing_if = "Option::is_none")]
    pub battle_boost: Option<bool>,
    #[serde(rename = "maxAllowableBans", skip_serializing_if = "Option::is_none")]
    pub max_allowable_bans: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl LolChampSelectLegacyQueueGameTypeConfig {
    pub fn new() -> LolChampSelectLegacyQueueGameTypeConfig {
        LolChampSelectLegacyQueueGameTypeConfig {
            allow_trades: None,
            battle_boost: None,
            max_allowable_bans: None,
            name: None,
        }
    }
}


