/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolHonorV2EndOfGamePlayer {
    #[serde(rename = "botPlayer", skip_serializing_if = "Option::is_none")]
    pub bot_player: Option<bool>,
    #[serde(rename = "championId", skip_serializing_if = "Option::is_none")]
    pub champion_id: Option<i32>,
    #[serde(rename = "gameId", skip_serializing_if = "Option::is_none")]
    pub game_id: Option<i64>,
    #[serde(rename = "isReportingDisabled", skip_serializing_if = "Option::is_none")]
    pub is_reporting_disabled: Option<bool>,
    #[serde(rename = "leaver", skip_serializing_if = "Option::is_none")]
    pub leaver: Option<bool>,
    #[serde(rename = "profileIconId", skip_serializing_if = "Option::is_none")]
    pub profile_icon_id: Option<i32>,
    #[serde(rename = "skinIndex", skip_serializing_if = "Option::is_none")]
    pub skin_index: Option<i32>,
    #[serde(rename = "skinName", skip_serializing_if = "Option::is_none")]
    pub skin_name: Option<String>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<serde_json::Value>,
    #[serde(rename = "summonerId", skip_serializing_if = "Option::is_none")]
    pub summoner_id: Option<i64>,
    #[serde(rename = "summonerName", skip_serializing_if = "Option::is_none")]
    pub summoner_name: Option<String>,
    #[serde(rename = "teamId", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i32>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    #[serde(rename = "wins", skip_serializing_if = "Option::is_none")]
    pub wins: Option<i32>,
}

impl LolHonorV2EndOfGamePlayer {
    pub fn new() -> LolHonorV2EndOfGamePlayer {
        LolHonorV2EndOfGamePlayer {
            bot_player: None,
            champion_id: None,
            game_id: None,
            is_reporting_disabled: None,
            leaver: None,
            profile_icon_id: None,
            skin_index: None,
            skin_name: None,
            stats: None,
            summoner_id: None,
            summoner_name: None,
            team_id: None,
            user_id: None,
            wins: None,
        }
    }
}


