/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLoyaltyGlobalRewards {
    #[serde(rename = "allChampions", skip_serializing_if = "Option::is_none")]
    pub all_champions: Option<bool>,
}

impl LolLoyaltyGlobalRewards {
    pub fn new() -> LolLoyaltyGlobalRewards {
        LolLoyaltyGlobalRewards {
            all_champions: None,
        }
    }
}


