/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClashPlayerTournamentData {
    #[serde(rename = "bracketId", skip_serializing_if = "Option::is_none")]
    pub bracket_id: Option<i64>,
    #[serde(rename = "isSub", skip_serializing_if = "Option::is_none")]
    pub is_sub: Option<bool>,
    #[serde(rename = "rosterId", skip_serializing_if = "Option::is_none")]
    pub roster_id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<crate::models::LolClashPlayerState>,
}

impl LolClashPlayerTournamentData {
    pub fn new() -> LolClashPlayerTournamentData {
        LolClashPlayerTournamentData {
            bracket_id: None,
            is_sub: None,
            roster_id: None,
            state: None,
        }
    }
}


