/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClubsClubDataDto {
    #[serde(rename = "clubKey", skip_serializing_if = "Option::is_none")]
    pub club_key: Option<String>,
    #[serde(rename = "createdTs", skip_serializing_if = "Option::is_none")]
    pub created_ts: Option<i64>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "jid", skip_serializing_if = "Option::is_none")]
    pub jid: Option<String>,
    #[serde(rename = "lastModifiedTs", skip_serializing_if = "Option::is_none")]
    pub last_modified_ts: Option<i64>,
    #[serde(rename = "motd", skip_serializing_if = "Option::is_none")]
    pub motd: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "permissionMap", skip_serializing_if = "Option::is_none")]
    pub permission_map: Option<crate::models::LolClubsClubPermissions>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl LolClubsClubDataDto {
    pub fn new() -> LolClubsClubDataDto {
        LolClubsClubDataDto {
            club_key: None,
            created_ts: None,
            description: None,
            jid: None,
            last_modified_ts: None,
            motd: None,
            name: None,
            permission_map: None,
            role: None,
            tag: None,
        }
    }
}


