/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolSuggestedPlayersSuggestedPlayersPlayerStatus {
    #[serde(rename = "currentLobbyStatus", skip_serializing_if = "Option::is_none")]
    pub current_lobby_status: Option<crate::models::LolSuggestedPlayersSuggestedPlayersLobbyStatus>,
    #[serde(rename = "lastQueuedLobbyStatus", skip_serializing_if = "Option::is_none")]
    pub last_queued_lobby_status: Option<crate::models::LolSuggestedPlayersSuggestedPlayersLobbyStatus>,
}

impl LolSuggestedPlayersSuggestedPlayersPlayerStatus {
    pub fn new() -> LolSuggestedPlayersSuggestedPlayersPlayerStatus {
        LolSuggestedPlayersSuggestedPlayersPlayerStatus {
            current_lobby_status: None,
            last_queued_lobby_status: None,
        }
    }
}


