/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolSummonerSummonerDto {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i64>,
    #[serde(rename = "expPoints", skip_serializing_if = "Option::is_none")]
    pub exp_points: Option<i32>,
    #[serde(rename = "expToNextLevel", skip_serializing_if = "Option::is_none")]
    pub exp_to_next_level: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nameChangeFlag", skip_serializing_if = "Option::is_none")]
    pub name_change_flag: Option<bool>,
    #[serde(rename = "partnerId", skip_serializing_if = "Option::is_none")]
    pub partner_id: Option<String>,
    #[serde(rename = "profileIconId", skip_serializing_if = "Option::is_none")]
    pub profile_icon_id: Option<i32>,
    #[serde(rename = "puuid", skip_serializing_if = "Option::is_none")]
    pub puuid: Option<String>,
}

impl LolSummonerSummonerDto {
    pub fn new() -> LolSummonerSummonerDto {
        LolSummonerSummonerDto {
            account_id: None,
            exp_points: None,
            exp_to_next_level: None,
            id: None,
            level: None,
            name: None,
            name_change_flag: None,
            partner_id: None,
            profile_icon_id: None,
            puuid: None,
        }
    }
}


