/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPftPftMetadata {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i64>,
    #[serde(rename = "appName", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(rename = "appVersion", skip_serializing_if = "Option::is_none")]
    pub app_version: Option<String>,
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<String>,
    #[serde(rename = "homepageTimer", skip_serializing_if = "Option::is_none")]
    pub homepage_timer: Option<f64>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<crate::models::LolPftPftEndOfGameStats>,
    #[serde(rename = "systemOs", skip_serializing_if = "Option::is_none")]
    pub system_os: Option<String>,
    #[serde(rename = "webRegion", skip_serializing_if = "Option::is_none")]
    pub web_region: Option<String>,
}

impl LolPftPftMetadata {
    pub fn new() -> LolPftPftMetadata {
        LolPftPftMetadata {
            account_id: None,
            app_name: None,
            app_version: None,
            env: None,
            homepage_timer: None,
            locale: None,
            stats: None,
            system_os: None,
            web_region: None,
        }
    }
}


