/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPremadeVoiceSettingsResource {
    #[serde(rename = "autoJoin", skip_serializing_if = "Option::is_none")]
    pub auto_join: Option<bool>,
    #[serde(rename = "currentCaptureDeviceHandle", skip_serializing_if = "Option::is_none")]
    pub current_capture_device_handle: Option<String>,
    #[serde(rename = "inputMode", skip_serializing_if = "Option::is_none")]
    pub input_mode: Option<crate::models::LolPremadeVoiceInputMode>,
    #[serde(rename = "localMicMuted", skip_serializing_if = "Option::is_none")]
    pub local_mic_muted: Option<bool>,
    #[serde(rename = "loopbackEnabled", skip_serializing_if = "Option::is_none")]
    pub loopback_enabled: Option<bool>,
    #[serde(rename = "micLevel", skip_serializing_if = "Option::is_none")]
    pub mic_level: Option<i32>,
    #[serde(rename = "muteOnConnect", skip_serializing_if = "Option::is_none")]
    pub mute_on_connect: Option<bool>,
    #[serde(rename = "pttActive", skip_serializing_if = "Option::is_none")]
    pub ptt_active: Option<bool>,
    #[serde(rename = "pttKey", skip_serializing_if = "Option::is_none")]
    pub ptt_key: Option<String>,
    #[serde(rename = "vadActive", skip_serializing_if = "Option::is_none")]
    pub vad_active: Option<bool>,
    #[serde(rename = "vadHangoverTime", skip_serializing_if = "Option::is_none")]
    pub vad_hangover_time: Option<i32>,
    #[serde(rename = "vadSensitivity", skip_serializing_if = "Option::is_none")]
    pub vad_sensitivity: Option<i32>,
}

impl LolPremadeVoiceSettingsResource {
    pub fn new() -> LolPremadeVoiceSettingsResource {
        LolPremadeVoiceSettingsResource {
            auto_join: None,
            current_capture_device_handle: None,
            input_mode: None,
            local_mic_muted: None,
            loopback_enabled: None,
            mic_level: None,
            mute_on_connect: None,
            ptt_active: None,
            ptt_key: None,
            vad_active: None,
            vad_hangover_time: None,
            vad_sensitivity: None,
        }
    }
}


