/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClubsRosterItemDto {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i64>,
    #[serde(rename = "clubRole", skip_serializing_if = "Option::is_none")]
    pub club_role: Option<String>,
    #[serde(rename = "summonerIconId", skip_serializing_if = "Option::is_none")]
    pub summoner_icon_id: Option<i32>,
    #[serde(rename = "summonerName", skip_serializing_if = "Option::is_none")]
    pub summoner_name: Option<String>,
}

impl LolClubsRosterItemDto {
    pub fn new() -> LolClubsRosterItemDto {
        LolClubsRosterItemDto {
            account_id: None,
            club_role: None,
            summoner_icon_id: None,
            summoner_name: None,
        }
    }
}


