/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolEndOfGameLoginDataPacket {
    #[serde(rename = "allSummonerData", skip_serializing_if = "Option::is_none")]
    pub all_summoner_data: Option<crate::models::LolEndOfGameLoginSummonerData>,
    #[serde(rename = "platformId", skip_serializing_if = "Option::is_none")]
    pub platform_id: Option<String>,
    #[serde(rename = "simpleMessages", skip_serializing_if = "Option::is_none")]
    pub simple_messages: Option<Vec<crate::models::LolEndOfGameSimpleMessage>>,
}

impl LolEndOfGameLoginDataPacket {
    pub fn new() -> LolEndOfGameLoginDataPacket {
        LolEndOfGameLoginDataPacket {
            all_summoner_data: None,
            platform_id: None,
            simple_messages: None,
        }
    }
}


