/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolBannersSummonerProfileUpdate {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl LolBannersSummonerProfileUpdate {
    pub fn new() -> LolBannersSummonerProfileUpdate {
        LolBannersSummonerProfileUpdate {
            key: None,
            value: None,
        }
    }
}


