/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolInventorySimpleInventoryDto {
    #[serde(rename = "expires", skip_serializing_if = "Option::is_none")]
    pub expires: Option<String>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "itemsJwt", skip_serializing_if = "Option::is_none")]
    pub items_jwt: Option<String>,
}

impl LolInventorySimpleInventoryDto {
    pub fn new() -> LolInventorySimpleInventoryDto {
        LolInventorySimpleInventoryDto {
            expires: None,
            items: None,
            items_jwt: None,
        }
    }
}


