/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolCollectionsSummonerProfile {
    #[serde(rename = "backgroundSkinId", skip_serializing_if = "Option::is_none")]
    pub background_skin_id: Option<i32>,
}

impl LolCollectionsSummonerProfile {
    pub fn new() -> LolCollectionsSummonerProfile {
        LolCollectionsSummonerProfile {
            background_skin_id: None,
        }
    }
}


