/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPremadeVoiceParticipantResource {
    #[serde(rename = "energy", skip_serializing_if = "Option::is_none")]
    pub energy: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "isMuted", skip_serializing_if = "Option::is_none")]
    pub is_muted: Option<bool>,
    #[serde(rename = "isSpeaking", skip_serializing_if = "Option::is_none")]
    pub is_speaking: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<i32>,
}

impl LolPremadeVoiceParticipantResource {
    pub fn new() -> LolPremadeVoiceParticipantResource {
        LolPremadeVoiceParticipantResource {
            energy: None,
            id: None,
            is_muted: None,
            is_speaking: None,
            name: None,
            volume: None,
        }
    }
}


