/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolRankedEosNotificationResource {
    #[serde(rename = "notificationName", skip_serializing_if = "Option::is_none")]
    pub notification_name: Option<String>,
    #[serde(rename = "notificationType", skip_serializing_if = "Option::is_none")]
    pub notification_type: Option<i32>,
    #[serde(rename = "queue", skip_serializing_if = "Option::is_none")]
    pub queue: Option<String>,
    #[serde(rename = "seasonEndTime", skip_serializing_if = "Option::is_none")]
    pub season_end_time: Option<i64>,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
}

impl LolRankedEosNotificationResource {
    pub fn new() -> LolRankedEosNotificationResource {
        LolRankedEosNotificationResource {
            notification_name: None,
            notification_type: None,
            queue: None,
            season_end_time: None,
            tier: None,
        }
    }
}


