/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLobbyTeamBuilderTbLobbyEnabledFeaturesResource {
    #[serde(rename = "enabledFeatures", skip_serializing_if = "Option::is_none")]
    pub enabled_features: Option<Vec<String>>,
}

impl LolLobbyTeamBuilderTbLobbyEnabledFeaturesResource {
    pub fn new() -> LolLobbyTeamBuilderTbLobbyEnabledFeaturesResource {
        LolLobbyTeamBuilderTbLobbyEnabledFeaturesResource {
            enabled_features: None,
        }
    }
}


