/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolSummonerSummonerCreatedId {
    #[serde(rename = "summonerId", skip_serializing_if = "Option::is_none")]
    pub summoner_id: Option<i64>,
}

impl LolSummonerSummonerCreatedId {
    pub fn new() -> LolSummonerSummonerCreatedId {
        LolSummonerSummonerCreatedId {
            summoner_id: None,
        }
    }
}


