/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolItemSetsPreferredItemSlot {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "preferredItemSlot", skip_serializing_if = "Option::is_none")]
    pub preferred_item_slot: Option<i32>,
}

impl LolItemSetsPreferredItemSlot {
    pub fn new() -> LolItemSetsPreferredItemSlot {
        LolItemSetsPreferredItemSlot {
            id: None,
            preferred_item_slot: None,
        }
    }
}


