/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolEmailVerificationRegionLocale {
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "webLanguage", skip_serializing_if = "Option::is_none")]
    pub web_language: Option<String>,
    #[serde(rename = "webRegion", skip_serializing_if = "Option::is_none")]
    pub web_region: Option<String>,
}

impl LolEmailVerificationRegionLocale {
    pub fn new() -> LolEmailVerificationRegionLocale {
        LolEmailVerificationRegionLocale {
            locale: None,
            region: None,
            web_language: None,
            web_region: None,
        }
    }
}


