/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLobbyPartyNotificationEnvelopeDto {
    #[serde(rename = "player", skip_serializing_if = "Option::is_none")]
    pub player: Option<crate::models::LolLobbyPlayerDto>,
    #[serde(rename = "queueRestriction", skip_serializing_if = "Option::is_none")]
    pub queue_restriction: Option<crate::models::LolLobbyQueueRestrictionDto>,
}

impl LolLobbyPartyNotificationEnvelopeDto {
    pub fn new() -> LolLobbyPartyNotificationEnvelopeDto {
        LolLobbyPartyNotificationEnvelopeDto {
            player: None,
            queue_restriction: None,
        }
    }
}


