/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolCollectionsAcsChampionGames {
    #[serde(rename = "championId", skip_serializing_if = "Option::is_none")]
    pub champion_id: Option<i32>,
    #[serde(rename = "queue", skip_serializing_if = "Option::is_none")]
    pub queue: Option<i32>,
}

impl LolCollectionsAcsChampionGames {
    pub fn new() -> LolCollectionsAcsChampionGames {
        LolCollectionsAcsChampionGames {
            champion_id: None,
            queue: None,
        }
    }
}


