/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChatQueue {
    #[serde(rename = "gameMode", skip_serializing_if = "Option::is_none")]
    pub game_mode: Option<String>,
    #[serde(rename = "gameTypeConfig", skip_serializing_if = "Option::is_none")]
    pub game_type_config: Option<crate::models::LolChatQueueGameTypeConfig>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl LolChatQueue {
    pub fn new() -> LolChatQueue {
        LolChatQueue {
            game_mode: None,
            game_type_config: None,
            id: None,
            _type: None,
        }
    }
}


