/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLeagueSessionLeagueSessionTokenEnvelope {
    #[serde(rename = "logoutOnFailure", skip_serializing_if = "Option::is_none")]
    pub logout_on_failure: Option<bool>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl LolLeagueSessionLeagueSessionTokenEnvelope {
    pub fn new() -> LolLeagueSessionLeagueSessionTokenEnvelope {
        LolLeagueSessionLeagueSessionTokenEnvelope {
            logout_on_failure: None,
            token: None,
        }
    }
}


