/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolRegaliaRegaliaPlatformConfig {
    #[serde(rename = "HovercardEnabled", skip_serializing_if = "Option::is_none")]
    pub hovercard_enabled: Option<bool>,
    #[serde(rename = "SelectionsEnabled", skip_serializing_if = "Option::is_none")]
    pub selections_enabled: Option<bool>,
}

impl LolRegaliaRegaliaPlatformConfig {
    pub fn new() -> LolRegaliaRegaliaPlatformConfig {
        LolRegaliaRegaliaPlatformConfig {
            hovercard_enabled: None,
            selections_enabled: None,
        }
    }
}


