/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolClubsPlayerClubMembership {
    #[serde(rename = "activeClubs", skip_serializing_if = "Option::is_none")]
    pub active_clubs: Option<Vec<crate::models::LolClubsPlayerClub>>,
    #[serde(rename = "clubsServerConfig", skip_serializing_if = "Option::is_none")]
    pub clubs_server_config: Option<crate::models::LolClubsClubsConfig>,
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<crate::models::LolClubsClubPlayer>,
    #[serde(rename = "pendingInvites", skip_serializing_if = "Option::is_none")]
    pub pending_invites: Option<Vec<crate::models::LolClubsClubInvite>>,
    #[serde(rename = "preferences", skip_serializing_if = "Option::is_none")]
    pub preferences: Option<crate::models::LolClubsClubPreferences>,
    #[serde(rename = "removedClubs", skip_serializing_if = "Option::is_none")]
    pub removed_clubs: Option<Vec<crate::models::LolClubsClub>>,
    #[serde(rename = "revokedInviteClubs", skip_serializing_if = "Option::is_none")]
    pub revoked_invite_clubs: Option<Vec<crate::models::LolClubsClub>>,
    #[serde(rename = "secureClubPresenceInfoString", skip_serializing_if = "Option::is_none")]
    pub secure_club_presence_info_string: Option<String>,
}

impl LolClubsPlayerClubMembership {
    pub fn new() -> LolClubsPlayerClubMembership {
        LolClubsPlayerClubMembership {
            active_clubs: None,
            clubs_server_config: None,
            info: None,
            pending_invites: None,
            preferences: None,
            removed_clubs: None,
            revoked_invite_clubs: None,
            secure_club_presence_info_string: None,
        }
    }
}


