/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPlayerBehaviorRestrictionNotification {
    #[serde(rename = "displayReformCard", skip_serializing_if = "Option::is_none")]
    pub display_reform_card: Option<bool>,
    #[serde(rename = "gamesRemaining", skip_serializing_if = "Option::is_none")]
    pub games_remaining: Option<i64>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<crate::models::LolPlayerBehaviorNotificationSource>,
}

impl LolPlayerBehaviorRestrictionNotification {
    pub fn new() -> LolPlayerBehaviorRestrictionNotification {
        LolPlayerBehaviorRestrictionNotification {
            display_reform_card: None,
            games_remaining: None,
            id: None,
            source: None,
        }
    }
}


