/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLobbyTeamBuilderTbRemovedFromServiceNotification {
    #[serde(rename = "backwardsTransitionInfo", skip_serializing_if = "Option::is_none")]
    pub backwards_transition_info: Option<crate::models::LolLobbyTeamBuilderBackwardsTransitionInfoV1>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl LolLobbyTeamBuilderTbRemovedFromServiceNotification {
    pub fn new() -> LolLobbyTeamBuilderTbRemovedFromServiceNotification {
        LolLobbyTeamBuilderTbRemovedFromServiceNotification {
            backwards_transition_info: None,
            reason: None,
        }
    }
}


