/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolLobbyTeamBuilderGameflowSession {
    #[serde(rename = "gameClient", skip_serializing_if = "Option::is_none")]
    pub game_client: Option<crate::models::LolLobbyTeamBuilderGameflowGameClient>,
}

impl LolLobbyTeamBuilderGameflowSession {
    pub fn new() -> LolLobbyTeamBuilderGameflowSession {
        LolLobbyTeamBuilderGameflowSession {
            game_client: None,
        }
    }
}


