/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolCatalogInventoryContent {
    #[serde(rename = "itemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i64>,
    #[serde(rename = "ownershipType", skip_serializing_if = "Option::is_none")]
    pub ownership_type: Option<crate::models::LolCatalogInventoryOwnership>,
    #[serde(rename = "purchaseDate", skip_serializing_if = "Option::is_none")]
    pub purchase_date: Option<String>,
}

impl LolCatalogInventoryContent {
    pub fn new() -> LolCatalogInventoryContent {
        LolCatalogInventoryContent {
            item_id: None,
            ownership_type: None,
            purchase_date: None,
        }
    }
}


