/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolChampionsCollectionsChampionSkinEmblem {
    #[serde(rename = "emblemPath", skip_serializing_if = "Option::is_none")]
    pub emblem_path: Option<crate::models::LolChampionsCollectionsChampionSkinEmblemPath>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "positions", skip_serializing_if = "Option::is_none")]
    pub positions: Option<crate::models::LolChampionsCollectionsChampionSkinEmblemPosition>,
}

impl LolChampionsCollectionsChampionSkinEmblem {
    pub fn new() -> LolChampionsCollectionsChampionSkinEmblem {
        LolChampionsCollectionsChampionSkinEmblem {
            emblem_path: None,
            name: None,
            positions: None,
        }
    }
}


