/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolGameQueuesQueueTranslation {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "detailedDescription", skip_serializing_if = "Option::is_none")]
    pub detailed_description: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "shortName", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<String>,
}

impl LolGameQueuesQueueTranslation {
    pub fn new() -> LolGameQueuesQueueTranslation {
        LolGameQueuesQueueTranslation {
            description: None,
            detailed_description: None,
            name: None,
            short_name: None,
        }
    }
}


