/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolRankedQueuesAndPuuidsPayload {
    #[serde(rename = "queueTypes", skip_serializing_if = "Option::is_none")]
    pub queue_types: Option<Vec<crate::models::LolRankedLeagueQueueType>>,
    #[serde(rename = "summonerIds", skip_serializing_if = "Option::is_none")]
    pub summoner_ids: Option<Vec<i64>>,
}

impl LolRankedQueuesAndPuuidsPayload {
    pub fn new() -> LolRankedQueuesAndPuuidsPayload {
        LolRankedQueuesAndPuuidsPayload {
            queue_types: None,
            summoner_ids: None,
        }
    }
}


