/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LolPlayerBehaviorNotificationSource {
    #[serde(rename = "Invalid")]
    Invalid,
    #[serde(rename = "Login")]
    Login,
    #[serde(rename = "ForcedShutdown")]
    ForcedShutdown,
    #[serde(rename = "Message")]
    Message,

}




