/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LolPerksPerkSubStyleBonusResource {
    #[serde(rename = "perkId", skip_serializing_if = "Option::is_none")]
    pub perk_id: Option<i32>,
    #[serde(rename = "styleId", skip_serializing_if = "Option::is_none")]
    pub style_id: Option<i32>,
}

impl LolPerksPerkSubStyleBonusResource {
    pub fn new() -> LolPerksPerkSubStyleBonusResource {
        LolPerksPerkSubStyleBonusResource {
            perk_id: None,
            style_id: None,
        }
    }
}


