/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LootItemListClientDto {
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<i64>,
    #[serde(rename = "lootItems", skip_serializing_if = "Option::is_none")]
    pub loot_items: Option<Vec<crate::models::LootItemClientDto>>,
}

impl LootItemListClientDto {
    pub fn new() -> LootItemListClientDto {
        LootItemListClientDto {
            last_update: None,
            loot_items: None,
        }
    }
}


