/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakingLcdsMatchMakerPayload {
    #[serde(rename = "LEAVER_BUSTER_ACCESS_TOKEN", skip_serializing_if = "Option::is_none")]
    pub LEAVER_BUSTER_ACCESS_TOKEN: Option<String>,
}

impl MatchmakingLcdsMatchMakerPayload {
    pub fn new() -> MatchmakingLcdsMatchMakerPayload {
        MatchmakingLcdsMatchMakerPayload {
            LEAVER_BUSTER_ACCESS_TOKEN: None,
        }
    }
}


