/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricMetadata {
    #[serde(rename = "alerts", skip_serializing_if = "Option::is_none")]
    pub alerts: Option<Vec<crate::models::MetricMetadataAlert>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "data_type", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<crate::models::MetricDataType>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<crate::models::MetricMetadataNotify>,
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    #[serde(rename = "pretty_name", skip_serializing_if = "Option::is_none")]
    pub pretty_name: Option<String>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<crate::models::MetricPriority>,
    #[serde(rename = "sample_window_ms", skip_serializing_if = "Option::is_none")]
    pub sample_window_ms: Option<i32>,
    #[serde(rename = "transientAggregation", skip_serializing_if = "Option::is_none")]
    pub transient_aggregation: Option<crate::models::AggregationType>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::MetricType>,
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
}

impl MetricMetadata {
    pub fn new() -> MetricMetadata {
        MetricMetadata {
            alerts: None,
            category: None,
            data_type: None,
            description: None,
            destination: None,
            info: None,
            notify: None,
            period: None,
            pretty_name: None,
            priority: None,
            sample_window_ms: None,
            transient_aggregation: None,
            _type: None,
            units: None,
        }
    }
}


