/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultipleReplayMetadataResponseV2 {
    #[serde(rename = "metadataResponses", skip_serializing_if = "Option::is_none")]
    pub metadata_responses: Option<Vec<crate::models::MultipleReplayMetadataResponseItemV2>>,
}

impl MultipleReplayMetadataResponseV2 {
    pub fn new() -> MultipleReplayMetadataResponseV2 {
        MultipleReplayMetadataResponseV2 {
            metadata_responses: None,
        }
    }
}


