/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalizedOffersLcdsChampionSkinDto {
    #[serde(rename = "championId", skip_serializing_if = "Option::is_none")]
    pub champion_id: Option<i32>,
    #[serde(rename = "owned", skip_serializing_if = "Option::is_none")]
    pub owned: Option<bool>,
    #[serde(rename = "skinId", skip_serializing_if = "Option::is_none")]
    pub skin_id: Option<i32>,
}

impl PersonalizedOffersLcdsChampionSkinDto {
    pub fn new() -> PersonalizedOffersLcdsChampionSkinDto {
        PersonalizedOffersLcdsChampionSkinDto {
            champion_id: None,
            owned: None,
            skin_id: None,
        }
    }
}


