/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayerMissionObjectiveDto {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "hasObjectiveBasedReward", skip_serializing_if = "Option::is_none")]
    pub has_objective_based_reward: Option<bool>,
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<crate::models::MissionProgressDto>,
    #[serde(rename = "requirements", skip_serializing_if = "Option::is_none")]
    pub requirements: Option<Vec<String>>,
    #[serde(rename = "rewardGroups", skip_serializing_if = "Option::is_none")]
    pub reward_groups: Option<Vec<String>>,
    #[serde(rename = "sequence", skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl PlayerMissionObjectiveDto {
    pub fn new() -> PlayerMissionObjectiveDto {
        PlayerMissionObjectiveDto {
            description: None,
            has_objective_based_reward: None,
            progress: None,
            requirements: None,
            reward_groups: None,
            sequence: None,
            status: None,
            _type: None,
        }
    }
}


