/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Position {
    #[serde(rename = "TOP")]
    TOP,
    #[serde(rename = "MIDDLE")]
    MIDDLE,
    #[serde(rename = "BOTTOM")]
    BOTTOM,
    #[serde(rename = "JUNGLE")]
    JUNGLE,
    #[serde(rename = "UTILITY")]
    UTILITY,
    #[serde(rename = "FILL")]
    FILL,
    #[serde(rename = "UNSELECTED")]
    UNSELECTED,

}




