/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecofrienderLinkResource {
    #[serde(rename = "linked", skip_serializing_if = "Option::is_none")]
    pub linked: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl RecofrienderLinkResource {
    pub fn new() -> RecofrienderLinkResource {
        RecofrienderLinkResource {
            linked: None,
            name: None,
            reason: None,
        }
    }
}


