/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RewardLogo {
    #[serde(rename = "logo", skip_serializing_if = "Option::is_none")]
    pub logo: Option<i32>,
    #[serde(rename = "memberOwnedCount", skip_serializing_if = "Option::is_none")]
    pub member_owned_count: Option<i32>,
}

impl RewardLogo {
    pub fn new() -> RewardLogo {
        RewardLogo {
            logo: None,
            member_owned_count: None,
        }
    }
}


