/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiotMessagingServiceSession {
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<crate::models::RiotMessagingServiceState>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "tokenType", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<crate::models::RiotMessagingServiceTokenType>,
}

impl RiotMessagingServiceSession {
    pub fn new() -> RiotMessagingServiceSession {
        RiotMessagingServiceSession {
            state: None,
            token: None,
            token_type: None,
        }
    }
}


