/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeasonSplitDto {
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    #[serde(rename = "rewardTrack", skip_serializing_if = "Option::is_none")]
    pub reward_track: Option<Vec<crate::models::SplitRewardGroupDto>>,
    #[serde(rename = "seasonId", skip_serializing_if = "Option::is_none")]
    pub season_id: Option<i32>,
    #[serde(rename = "splitId", skip_serializing_if = "Option::is_none")]
    pub split_id: Option<i32>,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
}

impl SeasonSplitDto {
    pub fn new() -> SeasonSplitDto {
        SeasonSplitDto {
            end_time: None,
            reward_track: None,
            season_id: None,
            split_id: None,
            start_time: None,
        }
    }
}


