/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TicketOfferDto {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "offerPlayerId", skip_serializing_if = "Option::is_none")]
    pub offer_player_id: Option<i64>,
    #[serde(rename = "receivePlayerId", skip_serializing_if = "Option::is_none")]
    pub receive_player_id: Option<i64>,
    #[serde(rename = "ticketOfferState", skip_serializing_if = "Option::is_none")]
    pub ticket_offer_state: Option<crate::models::TicketOfferState>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::TicketType>,
}

impl TicketOfferDto {
    pub fn new() -> TicketOfferDto {
        TicketOfferDto {
            count: None,
            offer_player_id: None,
            receive_player_id: None,
            ticket_offer_state: None,
            _type: None,
        }
    }
}


