/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TracingModuleTypeV1 {
    #[serde(rename = "kUnknown")]
    KUnknown,
    #[serde(rename = "kRemoteAppModule")]
    KRemoteAppModule,
    #[serde(rename = "kBackEndPlugin")]
    KBackEndPlugin,
    #[serde(rename = "kBackendOther")]
    KBackendOther,
    #[serde(rename = "kFrontEndPlugin")]
    KFrontEndPlugin,
    #[serde(rename = "kRemotingSource")]
    KRemotingSource,

}




